baseURL = "https://vsr625.github.io"
theme = "bearblog"
title = "Blog"
author = "Subramani Raju"
languageCode = "en-US"
enableRobotsTXT = false
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
sectionPagesMenu = "main"

[params]
description = "Blog"
title = "Blog"
